name: Auto message for PR's and Issues
description: Automatically send hello message to the first PR and Issue for new contributor.
branding:
  icon: message-square
  color: yellow
on: [pull_request, issues]
jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey, thank you for opening your first Issue ! 🙂 With the COVID-19 crisis, we have less people than usual to review the request so it may takes a little bit longuer. Sorry about that. Stay safe 😷!"
          pr-message: "Hey, thank you for opening your Pull Request ! With the COVID-19 crisis, we have less people than usual to review the request so it may takes a little bit longuer. Sorry about that. Stay safe 😷!"
